[package]
name = "4812571/component-binder"
version = "0.1.5"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Trove = "sleitnick/trove@1.1.0"
Observers = "sleitnick/observers@0.3.3"
Observe = "4812571/observe@0.2.3"
TableUtil = "sleitnick/table-util@1.2.0"
Signal = "sleitnick/signal@2.0.1"
Promise = "evaera/promise@4.0.0"